language: cpp
sudo:     required

services:
    - docker

cache:
  ccache: true
  directories:
    - $HOME/build-cache

matrix:
  include:
    - compiler: gcc
      env: TOOL=scons CXXSTD=14 NLS=true

    - compiler: gcc
      env: TOOL=scons CXXSTD=14 NLS=false OPT=-O0

    - compiler: gcc
      env: TOOL=cmake CXXSTD=14 NLS=false

    - compiler: clang
      env: TOOL=scons CXXSTD=14 NLS=false OPT=-O0

    - compiler: clang
      env: TOOL=cmake CXXSTD=14 NLS=false

    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env: TOOL=scons CXXSTD=14 NLS=false OPT=-O0

    - os: osx
      compiler: clang
      osx_image: xcode9.2
      env: TOOL=xcodebuild

install:
    - . ./utils/travis/steps/install.sh

script:
    - ./utils/travis/steps/script.sh
